# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" "dm_snapshot" ];
  boot.kernelModules = [ "kvm-intel" "fuse" "tun" "virtio" ];
  boot.extraModulePackages = [ ];
  boot.initrd.luks.devices = [
    { name = "root"; device = "/dev/nvme0n1p2"; preLVM = true; allowDiscards = true; }
    { name = "swap"; device = "/dev/nvme0n1p2"; preLVM = true; }
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0723a991-dfd2-4c3f-80f4-f970630d96b3";
      fsType = "ext4";
      options = [ "noatime" "nodiratime" "discard" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8970-A487";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
}
